In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])   #숫자형 벡터
b=np.array(["apple", "banana", "orange "])    #문자형 벡터
c=np.array([True, False, True, True])   #논리형 벡터

print("Numeric Vector:", a)
print("String Vector:", b)
print("Boolean Vector:", c)

Numeric Vector: [1 2 3 4 5]
String Vector: ['apple' 'banana' 'orange ']
Boolean Vector: [ True False  True  True]


In [ ]:
# 빈 배열 생성
x = np.empty(3)
print("빈 벡터 생성하기:", x)   # 메모리의 임의의 값을 가지며 시스템에 따라 다름

# 배열 채우기
x[0] = 3
x[1] = 5
x[2] = 3
print("채워진 벡터:", x)

빈 벡터 생성하기: [2.05833592e-312 2.05833592e-312 2.05833592e-312]
채워진 벡터: [3. 5. 3.]


In [ ]:
import numpy as np

arr1 = np.arange(10)
print("Array from 0 to 9:", arr1)

Array from 0 to 9: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2 = np.arange(0, 2, 0.5)
print("0부터 2 미만까지 0.5 간격으로 발생:", arr2)

0부터 2 미만까지 0.5 간격으로 발생: [0.  0.5 1.  1.5]


In [ ]:
linear_space1 = np.linspace(0, 1, 5)
print("0부터 1까지 5개 원소:", linear_space1)

0부터 1까지 5개 원소: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
linear_space2 = np.linspace(0, 1, 5, endpoint=False)
print("0부터 1까지 5개 원소, endpoint 제외:", linear_space2)

0부터 1까지 5개 원소, endpoint 제외: [0.  0.2 0.4 0.6 0.8]


In [ ]:
# 숫자 8을 4번 반복
repeated_vals = np.repeat(8, 4)
print("Repeated 8 four times:", repeated_vals)

Repeated 8 four times: [8 8 8 8]


In [ ]:
# 배열 [1,2,4]를 2번 반복
repeated_array = np.repeat([1,2,4], 2) # 배열을 평평하게 만든 후 반복
print("Repeated each element in [1,2,4] two times:", repeated_array)

# 배열 [1,2,4]의 각 요소를 각각 1,2,3번 반복
repeated_each = np.repeat([1,2,4], [1,2,3])
print("Repeated array [1, 2, 4] two times:", repeated_each)

Repeated each element in [1,2,4] two times: [1 1 2 2 4 4]
Repeated array [1, 2, 4] two times: [1 2 2 4 4 4]


In [ ]:
# 배열 [1,2,4]를 2회 반복(벡터 전체를 반복)
repeated_whole = np.tile([1,2,4], 2)
print("벡터 전체를 두 번 반복:", repeated_whole)

벡터 전체를 두 번 반복: [1 2 4 1 2 4]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5]) # 1차원 배열
len(a)

5

In [ ]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [ ]:
a = np.array([1,2,3,4,5])
a.size

5

In [ ]:
import numpy as np

# a를 랜덤하게 채움
np.random.seed(42)
a = np.random.randint(1, 21, 10)
print(a)
print(a[1])

[ 7 20 15 11  8  7 19 11 11  4]
20


In [ ]:
# 세 번째부터 다섯 번째 값 추출
print(a[2:5])

[15 11  8]


In [ ]:
# 첫 번째, 세 번째, 다섯 번째 값 추출
print(a[[0,2,4]])
# 두 번째 값 제외하고 추출
print(np.delete(a,1))

[ 7 15  8]
[ 7 15 11  8  7 19 11 11  4]


In [ ]:
# 인덱싱 중복 선택
print(a)
print(a[[1,1,3,2]])

[ 7 20 15 11  8  7 19 11 11  4]
[20 20 11 15]


In [ ]:
b = a[a>3]
print(b)

[ 7 20 15 11  8  7 19 11 11  4]


In [ ]:
b = a[(a>2) & (a<9)]
print(b)

[7 8 7 4]


In [ ]:
print(a[a== 8])
print(a[a!=8])

[8]
[ 7 20 15 11  7 19 11 11  4]


In [ ]:
print(~(a==8))
print(a[~(a==8)])

[ True  True  True  True False  True  True  True  True  True]
[ 7 20 15 11  7 19 11 11  4]


In [ ]:
b = a[np.arange(1,11) % 2 ==1]
print(b)

[ 7 15  8 19 11]


In [ ]:
b = a[a % 3 == 0]
print(b)

[15]


In [ ]:
x = np.array([True, True, False])
y = np.array([True, False, False])
print( x & y )

[ True False False]


In [ ]:
print( x | y )

[ True  True False]


In [3]:
import numpy as np
a = np.array([1,2,3,4,16,17,18])  #예시 배열

result = a[(a==4) & (a>15)]
print(result)

[]


In [4]:
result = a[(a==4) | (a>15)]
print(result)

[ 4 16 17 18]


In [5]:
import numpy as np
a = np.array([5,10,15,20,25,30])  # 예시 배열

a[a>=10] = 10
a

array([ 5, 10, 10, 10, 10, 10])

In [7]:
a = np.array([1,5,7,8,10])

result = a < 7
result

array([ True,  True, False, False, False])

In [8]:
result = np.where(a<7)
result

(array([0, 1]),)

In [16]:
import numpy as np
a = np.array([1,2,3,4,5])

sum_a = np.sum(a)   # 합계 계산
mean_a = np.mean(a)   # 평균 계산
median_a = np.median(a)   # 중앙값 계산
std_a = np.std(a, ddof=1)   # 표준편차 계산

print(sum_a, mean_a, median_a, std_a)

15 3.0 3.0 1.5811388300841898


In [17]:
a = np.array([20, np.nan, 13, 24, 309])   #데이터가 정의 되어 있지 않은 np.nan
a

array([ 20.,  nan,  13.,  24., 309.])

In [18]:
# nan 무시 옵션 가미 평균구하기

np.nanmean(a)

np.float64(91.5)

In [19]:
#nan과 None의 비교

import numpy as np

value = np.nan
if np.isnan(value):
    print("값이 NaN입니다.")

값이 NaN입니다.


In [20]:
value + 1   #수치 연산은 가능하나 결과는 nan

nan

In [21]:
my_variable = None
if my_variable is None:
  print("변수에 값이 없습니다.")

변수에 값이 없습니다.


In [22]:
None + 1     #수치 연산 불가

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [25]:
a = np.array([20, np.nan, 13, 24, 309])

a_filtered = a[~np.isnan(a)]
a_filtered

array([ 20.,  13.,  24., 309.])

In [26]:
str_vec = np.array(["사과", "배", "수박", "참외"])
str_vec                                                   # dtype에서 U2는 최대 2글자의 유니코드 문자열이라는 의미

array(['사과', '배', '수박', '참외'], dtype='<U2')

In [28]:
mix_vec = np.array(["사과", 12, "수박", "참외"], dtype=str)
mix_vec

array(['사과', '12', '수박', '참외'], dtype='<U2')

In [29]:
combined_vec = np.concatenate((str_vec, mix_vec))
combined_vec

array(['사과', '배', '수박', '참외', '사과', '12', '수박', '참외'], dtype='<U2')

In [32]:
col_stacked = np.column_stack((np.arange(1,5), np.arange(12,16)))
col_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [33]:
row_stacked = np.row_stack((np.arange(1,5), np.arange(12,16)))
row_stacked

<ipython-input-33-0b3558717fd9>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  row_stacked = np.row_stack((np.arange(1,5), np.arange(12,16)))


array([[ 1,  2,  3,  4],
       [12, 13, 14, 15]])

In [34]:
uneven_stacked = np.column_stack((np.arange(1,5), np.arange(12,18)))  #사이즈 안 맞아서 오류남

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 6

In [35]:
vec1 = np.arange(1,5)
vec2 = np.arange(12,18)
vec1 = np.resize(vec1, len(vec2))   #np.resize(a,len(b)) 하면 길이를 강제로 맞춰주고, 값을 a요소로 앞에서부터 채운다.
vec1

array([1, 2, 3, 4, 1, 2])

In [36]:
uneven_stacked = np.column_stack((vec1, vec2))
uneven_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 1, 16],
       [ 2, 17]])