In [1]:
import numpy as np

matrix = np.column_stack((np.arange(1,5), np.arange(12,16)))
print("행렬:\n", matrix)
print("행렬의 크기:", matrix.shape) # shape 속성으로 행렬의 크기 확인

행렬:
 [[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]]
행렬의 크기: (4, 2)


In [3]:
# 2행 2열의 빈 행렬 생성
y = np.zeros((2,2))
print("빈 행렬 y:\n", y)

빈 행렬 y:
 [[0. 0.]
 [0. 0.]]


In [5]:
# 1부터 4까지의 수로 채운 2행 2열 행렬 생성

y = np.arange(1,5).reshape(2,2)
print("1부터 4까지의 수로 채운 행렬 y:\n", y)

1부터 4까지의 수로 채운 행렬 y:
 [[1 2]
 [3 4]]


In [8]:
import numpy as np

# 두 개의 2x3 행렬 생성
mat1 = np.arange(1,7).reshape(2,3)
mat2 = np.arange(7,13).reshape(2,3)
print("행렬 mat1:\n", mat1)
print("행렬 mat2:\n", mat2)

행렬 mat1:
 [[1 2 3]
 [4 5 6]]
행렬 mat2:
 [[ 7  8  9]
 [10 11 12]]


In [9]:
# 3차원 배열로 합치기
my_array = np.array([mat1, mat2])
print("3차원 배열 my_array:\n", my_array)
print("3차원 배열의 크기 (shape):", my_array.shape)

3차원 배열 my_array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3차원 배열의 크기 (shape): (2, 2, 3)


In [10]:
import numpy as np

# 두 개의 2X3 행렬 생성
mat1 = np.arange(1,7).reshape(2,3)
mat2 = np.arange(7,13).reshape(2,3)

# 3차원 배열로 합치기
my_array = np.array([mat1, mat2])
print("3차원 배열 my_array:\n", my_array)

3차원 배열 my_array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# 첫 번째 2차원 배열 선택
first_slice = my_array[0,:,:]   # 첫번째 배열, 행과 열을 모두 살리라는 뜻
print("첫 번째 2차원 배열:\n", first_slice)

첫 번째 2차원 배열:
 [[1 2 3]
 [4 5 6]]


In [12]:
filtered_array = my_array[:,:,:-1]
print("세 번째 요소를 제외한 배열:\n", filtered_array)

세 번째 요소를 제외한 배열:
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [16]:
# 원래 배열
print("원래 배열 my_array:\n", my_array)

원래 배열 my_array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
my_array.shape

(2, 2, 3)

In [17]:
# 차원 변경

transposed_array = my_array.transpose(0,2,1)
print("차원이 변경된 배열:\n", transposed_array)

차원이 변경된 배열:
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [18]:
transposed_array.shape

(2, 3, 2)

In [20]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])

print("전체 합계:", a.sum())
print("열별 합계:", a.sum(axis=0))
print("행별 합계:", a.sum(axis=1))

전체 합계: 21
열별 합계: [5 7 9]
행별 합계: [ 6 15]


In [21]:
print("전체 평균:", a.mean())
print("열별 평균:", a.mean(axis=0))
print("행별 평균:", a.mean(axis=1))

전체 평균: 3.5
열별 평균: [2.5 3.5 4.5]
행별 평균: [2. 5.]


In [24]:
print("전체 최댓값", a.max())
print("열별 최댓값", a.max(axis=0))
print("행별 최댓값", a.max(axis=1))

전체 최댓값 6
열별 최댓값 [4 5 6]
행별 최댓값 [3 6]


In [25]:
print("전체 최솟값", a.min())
print("열별 최댓값", a.min(axis=0))
print("행별 최댓값", a.min(axis=1))

전체 최솟값 1
열별 최댓값 [1 2 3]
행별 최댓값 [1 4]


In [26]:
print("표본 표준편차 (ddof = 1):", a.std(ddof = 1))

표본 표준편차 (ddof = 1): 1.8708286933869707


In [27]:
print("표본 분산 (ddof = 1):", a.var(ddof=1))

표본 분산 (ddof = 1): 3.5


In [28]:
print("전체 누적 합계:", a.cumsum())
print("열별 누적 합계:", a.cumsum(axis=0))
print("행별 누적 합계:", a.cumsum(axis=1))

전체 누적 합계: [ 1  3  6 10 15 21]
열별 누적 합계: [[1 2 3]
 [5 7 9]]
행별 누적 합계: [[ 1  3  6]
 [ 4  9 15]]


In [30]:
print("전체 누적 곱:", a.cumprod())
print("열별 누적 곱:", a.cumprod(axis=0))
print("행별 누적 곱:", a.cumprod(axis=1))

전체 누적 곱: [  1   2   6  24 120 720]
열별 누적 곱: [[ 1  2  3]
 [ 4 10 18]]
행별 누적 곱: [[  1   2   6]
 [  4  20 120]]


In [31]:
print("최댓값의 인덱스 (전체):", a.argmax())
print("최댓값의 인덱스 (열별):", a.argmax(axis=0))
print("최댓값의 인덱스 (행별):", a.argmax(axis=1))

최댓값의 인덱스 (전체): 5
최댓값의 인덱스 (열별): [1 1 1]
최댓값의 인덱스 (행별): [2 2]


In [33]:
print("최솟값의 인덱스 (전체):", a.argmin())
print("최솟값의 인덱스 (열별):", a.argmin(axis=0))
print("최솟값의 인덱스 (행별):", a.argmin(axis=1))

최솟값의 인덱스 (전체): 0
최솟값의 인덱스 (열별): [0 0 0]
최솟값의 인덱스 (행별): [0 0]


In [34]:
b = np.array([1,2,3,4,5,6])
print("원본 배열:\n", b)
print("형상 변경:\n", b.reshape(2,3))

원본 배열:
 [1 2 3 4 5 6]
형상 변경:
 [[1 2 3]
 [4 5 6]]


In [35]:
c = np.array([[1,2,3], [4,5,6]])
print("원본 배열:\n", c)
print("전치 배열:\n", c.transpose())

원본 배열:
 [[1 2 3]
 [4 5 6]]
전치 배열:
 [[1 4]
 [2 5]
 [3 6]]


In [36]:
print("1차원 배열:\n", c.flatten()) #1차원 배열

1차원 배열:
 [1 2 3 4 5 6]


In [37]:
d = np.array([1,2,3,4,5])
print("클립된 배열:", d.clip(2,4))

클립된 배열: [2 2 3 4 4]


In [38]:
print("리스트:", d.tolist())

리스트: [1, 2, 3, 4, 5]


In [40]:
e = np.array([1.1,2.2,3.3])
print("정수형 배열:", e.astype(int))

정수형 배열: [1 2 3]


In [41]:
f = d.copy()
print("복사본 배열:", f)

복사본 배열: [1 2 3 4 5]


In [42]:
#얕은 복사

d=np.array([1,2,3,4,5])
f = d # 얕은 복사
f[0] = 10
print("d:", d)
print("f:", f)

d: [10  2  3  4  5]
f: [10  2  3  4  5]


In [43]:
d = np.array([1,2,3,4,5])
f = d.copy() # 깊은 복사
f[0] = 10
print("d:", d)
print("f:", f)

d: [1 2 3 4 5]
f: [10  2  3  4  5]


In [44]:
g = np.array([3,1,2])
g.sort()
print("정렬된 배열:", g)

정렬된 배열: [1 2 3]


In [45]:
h = np.array([3,1,2])
print("정렬된 인덱스:", h.argsort())

정렬된 인덱스: [1 2 0]


In [46]:
h = np.array([10,5,8,1,7])

# 배열을 정렬했을 때의 인덱스
sorted_indices = h.argsort()
print("정렬 후 인덱스:", sorted_indices)

# 정렬된 배열을 인덱스를 사용해 출력
sorted_h = h[sorted_indices]
print("정렬된 배열:", sorted_h)

정렬 후 인덱스: [3 1 4 2 0]
정렬된 배열: [ 1  5  7  8 10]
