In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
b = a + 5
print(b)

[ 6  7  8  9 10]


In [2]:
a = np.array([12,21,35,48,5])
c = a[np.arange(1,6) % 2 == 1]
print(c)

[12 35  5]


In [7]:
a = np.array([1,22,93,64,54])
c = np.max(a)
print(c)

93


In [9]:
a = np.array([1,2,3,2,4,5,4,6])
d = np.unique(a)
print(d)

[1 2 3 4 5 6]


In [18]:
a = np.array([21,31,58])
b = np.array([24,44,67])
c = np.empty(a.size + b.size, dtype =a.dtype)
c[0::2] = a
c[1::2] = b
print(c)

[21 24 31 44 58 67]


In [20]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9])

c = a[:-1] + b
print(c)

[ 7  9 11 13]
