In [11]:
import numpy as np

a = np.array([3,5,7,2,3,6]).reshape(2,3)
print("행렬 A:\n", a)

행렬 A:
 [[3 5 7]
 [2 3 6]]


In [20]:
B = np.array([[8,10,7,8],[2,4,5,5],[7,6,1,7], [2,6,8,6], [9,3,4,2]])
C = B[[1,3,4],:]
print(C)

[[2 4 5 5]
 [2 6 8 6]
 [9 3 4 2]]


In [22]:
B = np.array([[8,10,7,8],[2,4,5,5],[7,6,1,7], [2,6,8,6], [9,3,4,2]])
D = B[B[:,2]>3, :]
print(D)

[[ 8 10  7  8]
 [ 2  4  5  5]
 [ 2  6  8  6]
 [ 9  3  4  2]]


In [28]:
# 각 행별 합계 계산
row_sums = np.sum(B, axis = 1)
print(row_sums)

K = B[row_sums>=20,:]
print(K)

[33 16 21 22 18]
[[ 8 10  7  8]
 [ 7  6  1  7]
 [ 2  6  8  6]]


In [36]:
G = np.mean(B, axis=0)
print(G)

col_indices = np.where(G >= 5)[0]
print(col_indices)

[5.6 5.8 5.  5.6]
[0 1 2 3]


In [40]:
print("7보다 큰 숫자가 있는 행들:\n", B[np.sum(B>7, axis=1) > 0, :])

7보다 큰 숫자가 있는 행들:
 [[ 8 10  7  8]
 [ 2  6  8  6]
 [ 9  3  4  2]]
